version: '3.7'

services:
  frontend:
    build:
      context: .
    command: bash -c "npm run build && npm run preview"
    environment:
      - VITE_API_URL=http://ec2-18-170-30-106.eu-west-2.compute.amazonaws.com:8000/api/v1
      - VITE_FRONTEND_URL=http://ec2-18-170-30-106.eu-west-2.compute.amazonaws.com:3000/
