version: '3.7'

services:
    frontend:
      build:
        context: .
      volumes:
        - ./:/frontend:delegated
        - /node_modules
      ports:
        - 3000:3000
      networks:
        - app-network
      environment:
        - CHOKIDAR_USEPOLLING=true
        - WATCHPACK_POLLING=true

networks:
  app-network:
    driver: bridge